Feature/month coupon view
NHN-BookPub/bookpub-front pull request #67
Opened 2023-02-01 13:36 UTC by seohyeon07

마이페이지 내 쿠폰 조회 뷰 와 사이드바 고정으로 수정하였습니다.

2023-02-01 15:57 UTC, unhas01 approved these changes
수고하셨습니다.

2023-02-01 15:57 UTC, unhas01 commented on src/main/java/com/nhnacademy/bookpub/bookpubfront/coupon/adaptor/impl/CouponAdaptorImpl.java
> +    }
Util에 checkError() 있습니다.
그걸로 바꿔 주시고 아래 static은 지워주세요

2023-02-01 15:57 UTC, unhas01 commented on src/main/java/com/nhnacademy/bookpub/bookpubfront/coupon/service/impl/CouponServiceImpl.java
> +    }
Java Doc 없습니다.

2023-02-02 00:51 UTC, seohyeon07 commented on src/main/java/com/nhnacademy/bookpub/bookpubfront/coupon/adaptor/impl/CouponAdaptorImpl.java
> +    }
수정했습니다.

2023-02-02 00:52 UTC, seohyeon07 commented on src/main/java/com/nhnacademy/bookpub/bookpubfront/coupon/service/impl/CouponServiceImpl.java
> +    }
추가했습니다.

2023-02-02 01:05 UTC, hobby3530 requested changes
수고하셨습니다!

2023-02-02 01:05 UTC, hobby3530 approved these changes
수고하셨습니다!

2023-02-02 05:29 UTC, merged